services:
    # Laravel API Service
    app:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./backend:/var/www
            - ./backend/vendor:/var/www/vendor
        env_file:
            - .env.backend
        depends_on:
            - mysql

    # MySQL Database Service
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        env_file:
            - .env.mysql
        volumes:
            - mysql_data:/var/lib/mysql

    # React Frontend Service
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: react-frontend
        container_name: react-frontend
        restart: unless-stopped
        depends_on:
            - app
        ports:
            - '80:80'

    # Backend Nginx Service
    backend-nginx:
        image: nginx:alpine
        container_name: backend-nginx
        depends_on:
            - app
        volumes:
            - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default

volumes:
    mysql_data:
        driver: local
